### ISSUE TITLE
Feature Request: Uniform Rand

### ISSUE THREAD

**Issue by jdeshmukh** [decyphir/breach#3]
In addition to QuasiRandomSample(n), can Breach provide a UniformRandomSample(n)? This could utilize the Matlab-internal rand. The reason is that QuasiRandomSample gives signals that look too "not random" if you have a small sample. E.g. First few signals I get are always monotonically decreasing.

**Comment by adonze** [comment]
The SampleDomain generic method supports uniform random sampling. In BrDemo.AFC_3_Sets, there is an example of this: 
`BrAFC.SampleDomain({p_enum, p_double},{'all', 10}, 'rand');`
